wip: bulk analytics jsonl working

diff --git a/charts/gxa/templates/deployment.yaml b/charts/gxa/templates/deployment.yaml
--- a/charts/gxa/templates/deployment.yaml
+++ b/charts/gxa/templates/deployment.yaml
@@ -31,8 +31,10 @@ spec:
         {{- toYaml .Values.podSecurityContext | nindent 8 }}
       containers:
         - name: {{ include "app.name" . }}-webapp
+          {{- with .Values.securityContext }}
           securityContext:
-            {{- toYaml .Values.securityContext | nindent 12 }}
+            {{- toYaml . | nindent 12 }}
+          {{- end }}
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           ports:
@@ -67,7 +69,7 @@ spec:
                 secretKeyRef:
                   name: {{ include "app.fullname" . }}-secrets
                   key: SOLR_PASS
-            {{- /* These properties are required so that the bioentities SolrClient create 
+            {{- /* These properties are required so that the bioentities SolrClient create
              in the SolrConfig class is authenticated */}}
             - name: JAVA_TOOL_OPTIONS
               value: "-Dfile.encoding=UTF8 -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=\"$(SOLR_USER):$(SOLR_PASS)\""
@@ -87,7 +89,7 @@ spec:
               readOnly: true
             - name: gxa-codon-volume
               mountPath: {{ include "app.experimentsDir" . }}/species-properties.json
-              subPath: species-properties.json  
+              subPath: species-properties.json
               readOnly: true
             - name: services-volume
               mountPath: {{ include "app.dataDir" . }}/bioentity_properties
@@ -167,9 +169,11 @@ spec:
         - name: tomcat-config
           emptyDir: {}
       initContainers:
-        - name: {{ include "app.name" . }}-init-experiments-snapshot
+        - name: "{{ include "app.name" . }}-init-experiments-snapshot"
+          {{- with .Values.securityContext }}
           securityContext:
-            {{- toYaml .Values.securityContext | nindent 12 }}
+            {{- toYaml . | nindent 12 }}
+          {{- end }}
           image: busybox
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           command: ["sh"]
@@ -177,17 +181,22 @@ spec:
             - "-c"
             - |
               set -vx
-              ln -s -v {{ include "app.servicesDir" . }}/fg/atlas/{{ .Values.nfs.snapshotComponent }}/* /experiments_snapshot
+              EXPERIMENTS_SOURCE_DIR="{{- include "app.experimentsSourceDir" . -}}"
+              if [ ! -d "$EXPERIMENTS_SOURCE_DIR" ]; then
+                echo "ERROR: experimentsSourceDir does not exist: $EXPERIMENTS_SOURCE_DIR" >&2
+                exit 1
+              fi
+              echo "experimentsSourceDir exists: $EXPERIMENTS_SOURCE_DIR"
+              ln -s -v "$EXPERIMENTS_SOURCE_DIR"/* /experiments_snapshot
               ls -lt /experiments_snapshot
           volumeMounts:
             - name: gxa-codon-volume
               mountPath: {{ include "app.dataDir" . }}/gxa_codon
             - name: services-volume
-              {{- /* Use a template for the mountPath */}}
               mountPath: {{ include "app.servicesDir" . }}
             - name: experiments-snapshot
-              mountPath: /experiments_snapshot                 
-        - name: {{ include "app.name" . }}-init-tomcat-manager
+              mountPath: /experiments_snapshot
+        - name: "{{ include "app.name" . }}-init-tomcat-manager"
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           command: [ "sh"]
@@ -198,7 +207,7 @@ spec:
               cp -rv {{ include "app.tomcatDir" . }}/webapps.dist/manager {{ include "app.tomcatDir" . }}/webapps/
           volumeMounts:
             - name: tomcat-webapps
-              mountPath: {{ include "app.tomcatDir" . }}/webapps                 
+              mountPath: {{ include "app.tomcatDir" . }}/webapps
       {{- with .Values.nodeSelector }}
       nodeSelector:
         {{- toYaml . | nindent 8 }}
diff --git a/charts/gxa/templates/postgres-populator.yaml b/charts/gxa/templates/postgres-populator.yaml
--- a/charts/gxa/templates/postgres-populator.yaml
+++ b/charts/gxa/templates/postgres-populator.yaml
@@ -23,6 +23,11 @@ spec:
           image: openjdk:11
           securityContext:
             {{- toYaml .Values.securityContext | nindent 12 }}
+          {{- if .Values.debug.jvm }}
+          ports:
+            - containerPort: 5005
+              name: jdwp
+          {{- end }}
           env:
             - name: JAVA_TOOL_OPTIONS
               value: "-Dfile.encoding=UTF8"
@@ -52,30 +57,44 @@ spec:
 
               cd /atlas-web-bulk/
 
+              {{- if .Values.debug.enabled }}
+              set -v
+              {{- end }}
               mkdir {{ include "app.experimentsDir" . }}/magetab
-              ln -s {{ include "app.servicesDir" . }}/fg/atlas/{{ .Values.nfs.snapshotComponent }}/* \
-                    {{ include "app.experimentsDir" . }}/magetab 
-              ls -lt {{ include "app.experimentsDir" . }}/magetab 
-
-              ./gradlew \
-              {{ include "app.gradleCliArgs" . | indent 14 }} \
-              -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
-              -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
-              ":cli:bootRun" --args="create-update-experiment -e $(echo ${EXP_IDS})"
               
-              ./gradlew \
-              {{ include "app.gradleCliArgs" . | indent 14 }} \
-              -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
-              -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
-              ":cli:bootRun" --args="update-experiment-design -e $(echo ${EXP_IDS})"
-                            
-              ./gradlew \
-              {{ include "app.gradleCliArgs" . | indent 14 }} \
-              -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
-              -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
-              ":cli:bootRun" --args="update-baseline-coexpression -e $(echo ${EXP_IDS})"
+              EXPERIMENTS_SOURCE_DIR="{{- include "app.experimentsSourceDir" . -}}"
+              if [ ! -d "$EXPERIMENTS_SOURCE_DIR" ]; then
+                echo "ERROR: experimentsSourceDir does not exist: $EXPERIMENTS_SOURCE_DIR" >&2
+              else
+                echo "experimentsSourceDir exists: $EXPERIMENTS_SOURCE_DIR"
+                echo "found $(ls "$EXPERIMENTS_SOURCE_DIR" | wc -l) source experiments"
 
-              sleep 5000
+                ln -s "$EXPERIMENTS_SOURCE_DIR"/* \
+                      {{ include "app.experimentsDir" . }}/magetab 
+                echo "linked $(ls {{ include "app.experimentsDir" . }}/magetab | wc -l) experiments"
+
+                ./gradlew \
+                {{ include "app.gradleCliArgs" . | indent 14 }} \
+                -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
+                -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
+                ":cli:bootRun" --args="create-update-experiment -e $(echo ${EXP_IDS})"
+                
+                ./gradlew \
+                {{ include "app.gradleCliArgs" . | indent 14 }} \
+                -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
+                -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
+                ":cli:bootRun" --args="update-experiment-design -e $(echo ${EXP_IDS})"
+                              
+                ./gradlew \
+                {{ include "app.gradleCliArgs" . | indent 14 }} \
+                -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
+                -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
+                ":cli:bootRun" --args="update-baseline-coexpression -e $(echo ${EXP_IDS})"
+              fi
+
+              {{- if .Values.debug.enabled }}
+              sleep 50000
+              {{- end }}
           volumeMounts:
             - name: {{ include "app.name" . }}-expdesign-vol
               mountPath: "{{ include "app.expdesignDir" . }}"
@@ -84,7 +103,7 @@ spec:
             - name: services-volume
               mountPath: "{{ include "app.servicesDir" . }}"
             - name: {{ include "app.name" . }}-codon-volume
-              mountPath: "{{ include "app.experimentsDir" . }}/gxa-codon"
+              mountPath: "{{ include "app.dataDir" . }}/gxa_codon"
             - name: {{ include "app.name" . }}-codon-volume
               mountPath: "{{ include "app.experimentsDir" . }}/species-properties.json"
               subPath: species-properties.json  
diff --git a/charts/gxa/templates/solrcloud-bulk-analytics-jsonl.yaml b/charts/gxa/templates/solrcloud-bulk-analytics-jsonl.yaml
--- a/charts/gxa/templates/solrcloud-bulk-analytics-jsonl.yaml
+++ b/charts/gxa/templates/solrcloud-bulk-analytics-jsonl.yaml
@@ -25,8 +25,9 @@ spec:
       containers:
         - name: {{ include "app.name" . }}-solrcloud-bulk-analytics-jsonl
           image: openjdk:11
-          {{- /* Expose JDWP port if debug enabled */}}
-          {{- if .Values.debug.enabled }}
+          securityContext:
+            {{- toYaml .Values.securityContext | nindent 12 }}          {{- /* Expose JDWP port if debug enabled */}}
+          {{- if .Values.debug.jvm }}
           ports:
             - containerPort: 5005
               name: jdwp
@@ -93,29 +94,37 @@ spec:
 
               git clone --recurse-submodules --depth 1 --single-branch https://github.com/ebi-gene-expression-group/atlas-web-bulk.git
               cp /secrets/jdbc.properties \
-                 /secrets/solr.properties \
-                 /atlas-web-bulk/cli/src/main/resources/
+                  /secrets/solr.properties \
+                  /atlas-web-bulk/cli/src/main/resources/
 
               cd /atlas-web-bulk
 
               mkdir {{ include "app.experimentsDir" . }}/magetab
-              ln -s {{ include "app.servicesDir" . }}/fg/atlas/{{ .Values.nfs.snapshotComponent }}/* \
-                    {{ include "app.experimentsDir" . }}/magetab 
+              
+              EXPERIMENTS_SOURCE_DIR="{{- include "app.experimentsSourceDir" . -}}"
+              if [ ! -d "$EXPERIMENTS_SOURCE_DIR" ]; then
+                echo "ERROR: experimentsSourceDir does not exist: $EXPERIMENTS_SOURCE_DIR" >&2
+              else
+                echo "experimentsSourceDir exists: $EXPERIMENTS_SOURCE_DIR"
+                ln -s "$EXPERIMENTS_SOURCE_DIR"/* \
+                      {{ include "app.experimentsDir" . }}/magetab 
 
-              {{- if .Values.debug.enabled }}                    
-              set -v
-              {{- end }}
-              for EXP_IDS in HUMAN_EXP_IDS MOUSE_EXP_IDS ZEBRAFISH_EXP_IDS FLY_EXP_IDS WORM_EXP_IDS HORSE_EXP_IDS YEAST_EXP_IDS WHEAT_EXP_IDS PLATYPUS_EXP_IDS RICE_EXP_IDS GRASS_EXP_IDS SCHISTOSOME_EXP_IDS
-              do  
-                echo "Processing experiment IDs: ${EXP_IDS}"
-                ./gradlew --no-watch-fs --info \
-                -PdataFilesLocation={{ include "app.dataDir" . }} \
-                {{ include "app.gradleCliArgs" . | indent 14 }} \
-                -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
-                -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
-                :cli:bootRun {{- if .Values.debug.enabled }} --debug-jvm{{- end }} \
-                --args="bulk-analytics-json --output={{ include "app.bulkAnalyticsJsonlDir" . }} -e ${!EXP_IDS}"
-              done
+                {{- if .Values.debug.enabled }}
+                echo "found $(ls {{ include "app.experimentsDir" . }}/magetab | wc -l) experiments"                 
+                set -v
+                {{- end }}
+                for EXP_IDS in HUMAN_EXP_IDS MOUSE_EXP_IDS ZEBRAFISH_EXP_IDS FLY_EXP_IDS WORM_EXP_IDS HORSE_EXP_IDS YEAST_EXP_IDS WHEAT_EXP_IDS PLATYPUS_EXP_IDS RICE_EXP_IDS GRASS_EXP_IDS SCHISTOSOME_EXP_IDS
+                do  
+                  echo "Processing experiment IDs: ${EXP_IDS}"
+                  ./gradlew --no-watch-fs --info \
+                  -PdataFilesLocation={{ include "app.dataDir" . }} \
+                  {{ include "app.gradleCliArgs" . | indent 14 }} \
+                  -PexperimentFilesLocation={{ include "app.experimentsDir" . }} \
+                  -PexperimentDesignLocation={{ include "app.expdesignDir" . }} \
+                  :cli:bootRun {{- if .Values.debug.jvm }} --debug-jvm{{- end }} \
+                  --args="bulk-analytics-json --output={{ include "app.bulkAnalyticsJsonlDir" . }} -e ${!EXP_IDS}"
+                done
+              fi
               {{- if .Values.debug.enabled }}
               sleep 60000
               {{- end }}
@@ -130,6 +139,9 @@ spec:
               mountPath: {{ include "app.experimentsDir" . }}/species-properties.json
               subPath: species-properties.json  
               readOnly: true
+            - name: {{ include "app.name" . }}-codon-volume
+              mountPath: {{ include "app.dataDir" . }}/gxa_codon
+              readOnly: true
             - mountPath: "{{ include "app.bulkAnalyticsJsonlDir" . }}"
               name: bulk-analytics-jsonl-vol
             - name: webapp-volume
@@ -141,9 +153,19 @@ spec:
               mountPath: /secrets/jdbc.properties
               subPath: jdbc.properties
 
-      {{/* only wait for previous job if it is enabled */}}
-      {{- if and .Values.solr .Values.solr.bioentities.populator .Values.solr.bioentities.populator.enabled | default false -}}
+      {{/* only wait for previous jobs if they are enabled */}}
       initContainers:
+      {{ if and .Values.solr .Values.solr.bioentities.populator .Values.solr.bioentities.populator.enabled | default false }}
+      - name: wait-for-previous-job
+        image: dtzar/helm-kubectl:3.16.2
+        command: ["kubectl"]
+        args:
+        - "wait"
+        - "--for=condition=complete"
+        - "--timeout=1h"
+        - "job/bioentities-populator"
+      {{- end }}
+      {{ if and .Values.solr .Values.jdbc.populator .Values.jdbc.populator.enabled | default false }}
       - name: wait-for-previous-job
         image: dtzar/helm-kubectl:3.16.2
         command: ["kubectl"]
